PROJECT_ROOT ?= $(abspath ..)
include $(PROJECT_ROOT)/build/def.mk

SUBDIRS += chapter1 chapter2 chapter3 chapter4 chapter5 chapter7 chapter8
SUBDIRS += chapter9 chapter10 chapter14 chapter15

include $(PROJECT_ROOT)/build/subdir.mk
